version: '3'

services:
  web-app:
    image: rathneesh/hit-counter 

    ports:
      - 5000:5000
    networks:
      - mynet
  redis:
    image: redis
    networks:
      - mynet
    volumes:
      - mydata:/data

networks:
  mynet:
volumes:
  mydata:    
